### ISSUE TITLE
Deciding Game Winner

### ISSUE THREAD

**Issue by jameslulay** [Reivax2003/TexasHoldemCS301#4]
The game cannot properly decide a winner. It can't read the quality of a hand outside of merely the value of an individual card.  It can't sense if any hand, such as a full house or a straight, is actually present. It can detect if the two players have even "highest cards", however, which is good. 

When I look in the code, there is an "EvaluateHand" class that seems mostly complete. However, when I hit cntrl on it to see when it's used, it's only ever used in the unit tests. I think there is a stand in method doing the work somewhere else at the moment where this is supposed to be called. Most of the work has been done in it, so I think it was just forgotten to be instantiated and used somewhere.

**Comment by Reivax2003** [comment]
The game now correctly evaluates the player's hand at the end of the game.
