### ISSUE TITLE
Lacks ante button. I am incapable of "checking".

### ISSUE THREAD

**Issue by jameslulay** [Reivax2003/TexasHoldemCS301#5]
After "the flop", I cannot simply "check". By this I mean bet nothing. I would recommend fixing this bug by putting in a dedicated "check"  button that becomes available when you actually have the option to do so.

Also, since this is texas hold em, there needs to be an "ante in". I recommend you just have this be automatic at the beginning of every round.

**Comment by Reivax2003** [comment]
The bet button now changes to "check" when the amount to be bet would result in the betting player matching the current highest bet. Instead of an ante texas holdem generally uses a blind bet, which has also been implemented.
